#index:
#    path: /
#    controller: App\Controller\DefaultController::index
test:
  path: /getTestData
  controller: App\Controller\TestController::getTestData

getUsers:
  path: /getAllUsers
  controller: App\Controller\TestController::getUsers