name: MASTER_PUSH_DEPLOY

on: 
  push:
    branches: 
      - master

jobs:
  build:
    name: DEPLOYING
    runs-on: ubuntu-latest

    steps:
    - name: makegit pull origin master
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWD }}
          script: cd ~/Projects/wallet-core && git pull origin master && composer update
